services:
  backend:
    image: 631595683567.dkr.ecr.eu-north-1.amazonaws.com/markorudovic/devops-lab-backend:latest
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: 631595683567.dkr.ecr.eu-north-1.amazonaws.com/markorudovic/devops-lab-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped