name: CI/CD to ECR (OIDC) - backend + frontend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Docker build (uvijek, i za PR i za push)
      - name: Docker build (backend)
        run: |
          docker build -t backend:${{ github.sha }} -f backend/Dockerfile backend

      - name: Docker build (frontend)
        run: |
          docker build -t frontend:${{ github.sha }} -f frontend/Dockerfile frontend

  cd:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_PUSH_ECR_ROLA }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag and push (backend)
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPO: ${{ secrets.ECR_REPOSITORY_BACKEND }}
          SHA: ${{ github.sha }}
        run: |
          set -euo pipefail
          ECR_REGISTRY_CLEAN="$(echo -n "$ECR_REGISTRY" | tr -d '\r\n' | xargs)"
          ECR_REPO_CLEAN="$(echo -n "$ECR_REPO" | tr -d '\r\n' | xargs)"

          IMAGE_SHA="$ECR_REGISTRY/$ECR_REPO:$SHA"
          IMAGE_LATEST="$ECR_REGISTRY/$ECR_REPO:latest"

          docker build -t "$IMAGE_SHA" -t "$IMAGE_LATEST" -f backend/Dockerfile backend
          docker push "$IMAGE_SHA"
          docker push "$IMAGE_LATEST"

      - name: Build, tag and push (frontend)
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPO: ${{ secrets.ECR_REPOSITORY_FRONTEND }}
          SHA: ${{ github.sha }}
        run: |
          set -euo pipefail
          ECR_REGISTRY_CLEAN="$(echo -n "$ECR_REGISTRY" | tr -d '\r\n' | xargs)"
          ECR_REPO_CLEAN="$(echo -n "$ECR_REPO" | tr -d '\r\n' | xargs)"

          IMAGE_SHA="$ECR_REGISTRY/$ECR_REPO:$SHA"
          IMAGE_LATEST="$ECR_REGISTRY/$ECR_REPO:latest"

          docker build -t "$IMAGE_SHA" -t "$IMAGE_LATEST" -f frontend/Dockerfile frontend
          docker push "$IMAGE_SHA"
          docker push "$IMAGE_LATEST"
